### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by JMS55** [NVIDIAGameWorks/SHARC#1]
Hi, I've been working on a RT-GI renderer for the open source [Bevy game engine](https://github.com/bevyengine/bevy/pull/10000). I'm also using a spatial hashing based radiance cache, and would love to compare implementations and learn from your code. However, the current license would not allow that.

> Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited. 

Would it be possible to add an open source (preferably MIT/Apache) license to this repo?

Thanks a ton for your open source RT-GI research, SHaRC or no!

**Comment by emakarov-cmd** [comment]
@JMS55 please check the actual license content:
https://developer.download.nvidia.com/gameworks/NVIDIA_RTX_SDKs_License_12Apr2021.pdf

You must agree with it by setting a checkbox at:
https://developer.nvidia.com/rtx/ray-tracing/rtxgi/get-started

**Comment by JMS55** [comment]
Unfortunately, this prevents any usage in my open source (MIT+Apache) project, as I cannot distribute code derived from SHARC under the open source license. Thank you anyways.
